//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLamDep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailID { get; set; }
        public int InvoiceID { get; set; }
        public int? ServiceID { get; set; }
        public int Quantity { get; set; }
        public int? ProductID { get; set; } // ?? THÊM D?NG NÀY
        public decimal UnitPrice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Service Service { get; set; }
        public virtual Product Product { get; set; } // ?? N?u mu?n navigation

    }
}
